//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.WholeBackend {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WholeBackend.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        string BuyCurrency(string currencyCode, double plnAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<string> BuyCurrencyAsync(string currencyCode, double plnAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        string SellCurrency(string currencyCode, double currencyAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        System.Threading.Tasks.Task<string> SellCurrencyAsync(string currencyCode, double currencyAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPLNBalance", ReplyAction="http://tempuri.org/IService1/GetPLNBalanceResponse")]
        double GetPLNBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPLNBalance", ReplyAction="http://tempuri.org/IService1/GetPLNBalanceResponse")]
        System.Threading.Tasks.Task<double> GetPLNBalanceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrencyHoldings", ReplyAction="http://tempuri.org/IService1/GetCurrencyHoldingsResponse")]
        System.Collections.Generic.Dictionary<string, double> GetCurrencyHoldings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrencyHoldings", ReplyAction="http://tempuri.org/IService1/GetCurrencyHoldingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetCurrencyHoldingsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleClient.WholeBackend.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleClient.WholeBackend.IService1>, ConsoleClient.WholeBackend.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public string BuyCurrency(string currencyCode, double plnAmount) {
            return base.Channel.BuyCurrency(currencyCode, plnAmount);
        }
        
        public System.Threading.Tasks.Task<string> BuyCurrencyAsync(string currencyCode, double plnAmount) {
            return base.Channel.BuyCurrencyAsync(currencyCode, plnAmount);
        }
        
        public string SellCurrency(string currencyCode, double currencyAmount) {
            return base.Channel.SellCurrency(currencyCode, currencyAmount);
        }
        
        public System.Threading.Tasks.Task<string> SellCurrencyAsync(string currencyCode, double currencyAmount) {
            return base.Channel.SellCurrencyAsync(currencyCode, currencyAmount);
        }
        
        public double GetPLNBalance() {
            return base.Channel.GetPLNBalance();
        }
        
        public System.Threading.Tasks.Task<double> GetPLNBalanceAsync() {
            return base.Channel.GetPLNBalanceAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, double> GetCurrencyHoldings() {
            return base.Channel.GetCurrencyHoldings();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetCurrencyHoldingsAsync() {
            return base.Channel.GetCurrencyHoldingsAsync();
        }
    }
}
